--PLAYER 테이블에서 팀별 최대 몸무게인 선수의 
--TEAM_ID, REGION_NAME, PLAYER_NAME, WEIGTH 검색(WHERE IN 사용하기)
SELECT T.TEAM_ID, T.REGION_NAME, P.PLAYER_NAME, P.WEIGHT
FROM TEAM T, PLAYER P
WHERE P.TEAM_ID = T.TEAM_ID AND
(P.TEAM_ID, P.WEIGHT) IN 
(SELECT TEAM_ID, MAX(WEIGHT) FROM PLAYER GROUP BY TEAM_ID);

--DEPT 테이블의 LOC별 평균 급여를 반올림한 값과
--각 LOC별 SAL 총 합을 검색하기
SELECT D.LOC, ROUND(AVG(SAL)) "평균 급여", SUM(SAL) "총 급여"
FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
GROUP BY D.LOC;

--EMP 테이블에서 HIREDATE가 FORD의 입사년도와 같은 사원 전체 정보 검색
SELECT * FROM EMP E
WHERE TO_CHAR(HIREDATE, 'YYYY-MM-DD')
LIKE(
(SELECT SUBSTR(TO_CHAR(HIREDATE, 'YYYY-MM-DD'), 1, 4)
FROM EMP WHERE ENAME = 'FORD')||'%');

SELECT TO_CHAR(HIREDATE) FROM EMP WHERE ENAME = 'FORD';

--JOBS 테이블에서 JOB_TITLE별 사원들 평균 급여 검색
--JOB_TITLE로 정렬
--순서 : FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY
SELECT J.JOB_TITLE, AVG(E.SALARY)
FROM JOBS J JOIN EMPLOYEES E
ON J.JOB_ID = E.JOB_ID
GROUP BY JOB_TITLE
ORDER BY 1;

--AVG함수를 쓰지 않고 PLAYER 테이블에서 선수들 평균 키 구하기(NULL미포함)
SELECT ROUND(SUM(HEIGHT) / COUNT(HEIGHT)) 평균키 FROM PLAYER;

SELECT * FROM PLAYER;


